<a href="https://colab.research.google.com/github/Mohammed-Abdul-Rafe-Sajid/ML-LAB/blob/main/ML_LAB_10.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# ==============================================================
# OR Gate Neural Network using TensorFlow / Keras
# ==============================================================

import numpy as np
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.optimizers import SGD

# --------------------------------------------------------------
# 1️⃣ Prepare Dataset
# --------------------------------------------------------------
X = np.array([[0,0],
              [0,1],
              [1,0],
              [1,1]], dtype=float)

y = np.array([[0],
              [1],
              [1],
              [1]], dtype=float)

# --------------------------------------------------------------
# 2️⃣ Build Model
# --------------------------------------------------------------
model = Sequential()
model.add(Dense(1, input_dim=2, activation='sigmoid'))

# --------------------------------------------------------------
# 3️⃣ Compile Model
# --------------------------------------------------------------
model.compile(optimizer=SGD(learning_rate=0.1),
              loss='binary_crossentropy',
              metrics=['accuracy'])

# --------------------------------------------------------------
# 4️⃣ Train Model
# --------------------------------------------------------------
model.fit(X, y, epochs=5000, verbose=0)

# --------------------------------------------------------------
# 5️⃣ Test Model
# --------------------------------------------------------------
predictions = model.predict(X)
predicted_classes = (predictions > 0.5).astype(int)

print("Inputs:\n", X)
print("Predicted Outputs:\n", predictions)
print("Rounded Predictions (0/1):\n", predicted_classes)

# --------------------------------------------------------------
# 6️⃣ Show Weights and Bias
# --------------------------------------------------------------
weights, bias = model.layers[0].get_weights()
print("\nWeights:\n", weights)
print("Bias:\n", bias)


/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/dense.py:93: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 79ms/step
Inputs:
 [[0. 0.]
 [0. 1.]
 [1. 0.]
 [1. 1.]]
Predicted Outputs:
 [[0.04172406]
 [0.9833523 ]
 [0.9833833 ]
 [0.99998754]]
Rounded Predictions (0/1):
 [[0]
 [1]
 [1]
 [1]]

Weights:
 [[7.2146487]
 [7.212755 ]]
Bias:
 [-3.134058]


In [2]:
# ==============================================================
# AND Gate Neural Network using TensorFlow / Keras
# ==============================================================

import numpy as np
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.optimizers import SGD

# --------------------------------------------------------------
# 1️⃣ Prepare Dataset
# --------------------------------------------------------------
X = np.array([[0,0],
              [0,1],
              [1,0],
              [1,1]], dtype=float)

y = np.array([[0],
              [0],
              [0],
              [1]], dtype=float)

# --------------------------------------------------------------
# 2️⃣ Build Model
# --------------------------------------------------------------
model = Sequential()
model.add(Dense(1, input_dim=2, activation='sigmoid'))

# --------------------------------------------------------------
# 3️⃣ Compile Model
# --------------------------------------------------------------
model.compile(optimizer=SGD(learning_rate=0.1),
              loss='binary_crossentropy',
              metrics=['accuracy'])

# --------------------------------------------------------------
# 4️⃣ Train Model
# --------------------------------------------------------------
model.fit(X, y, epochs=5000, verbose=0)

# --------------------------------------------------------------
# 5️⃣ Test Model
# --------------------------------------------------------------
predictions = model.predict(X)
predicted_classes = (predictions > 0.5).astype(int)

print("Inputs:\n", X)
print("Predicted Outputs:\n", predictions)
print("Rounded Predictions (0/1):\n", predicted_classes)

# --------------------------------------------------------------
# 6️⃣ Show Weights and Bias
# --------------------------------------------------------------
weights, bias = model.layers[0].get_weights()
print("\nWeights:\n", weights)
print("Bias:\n", bias)


1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 53ms/step
Inputs:
 [[0. 0.]
 [0. 1.]
 [1. 0.]
 [1. 1.]]
Predicted Outputs:
 [[1.01352765e-04]
 [3.97810861e-02]
 [3.97805423e-02]
 [9.44236040e-01]]
Rounded Predictions (0/1):
 [[0]
 [0]
 [0]
 [1]]

Weights:
 [[6.013018 ]
 [6.0130324]]
Bias:
 [-9.196802]


In [3]:
# ==============================================================
# XOR Gate Neural Network using TensorFlow / Keras
# ==============================================================

import numpy as np
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.optimizers import SGD

# --------------------------------------------------------------
# 1️⃣ Prepare Dataset
# --------------------------------------------------------------
X = np.array([[0,0],
              [0,1],
              [1,0],
              [1,1]], dtype=float)

y = np.array([[0],
              [1],
              [1],
              [0]], dtype=float)

# --------------------------------------------------------------
# 2️⃣ Build Model (needs hidden layer)
# --------------------------------------------------------------
model = Sequential()
model.add(Dense(2, input_dim=2, activation='sigmoid'))  # hidden layer with 2 neurons
model.add(Dense(1, activation='sigmoid'))               # output layer

# --------------------------------------------------------------
# 3️⃣ Compile Model
# --------------------------------------------------------------
model.compile(optimizer=SGD(learning_rate=0.1),
              loss='binary_crossentropy',
              metrics=['accuracy'])

# --------------------------------------------------------------
# 4️⃣ Train Model
# --------------------------------------------------------------
model.fit(X, y, epochs=10000, verbose=0)

# --------------------------------------------------------------
# 5️⃣ Test Model
# --------------------------------------------------------------
predictions = model.predict(X)
predicted_classes = (predictions > 0.5).astype(int)

print("Inputs:\n", X)
print("Predicted Outputs:\n", predictions)
print("Rounded Predictions (0/1):\n", predicted_classes)

# --------------------------------------------------------------
# 6️⃣ Show Weights and Bias
# --------------------------------------------------------------
for i, layer in enumerate(model.layers):
    weights, bias = layer.get_weights()
    print(f"\nLayer {i+1} Weights:\n", weights)
    print(f"Layer {i+1} Bias:\n", bias)


1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 68ms/step
Inputs:
 [[0. 0.]
 [0. 1.]
 [1. 0.]
 [1. 1.]]
Predicted Outputs:
 [[0.01034662]
 [0.4961489 ]
 [0.98951155]
 [0.5039937 ]]
Rounded Predictions (0/1):
 [[0]
 [0]
 [1]
 [1]]

Layer 1 Weights:
 [[ 3.9434495 -4.236008 ]
 [-7.2929096 -7.180915 ]]
Layer 1 Bias:
 [-2.599403   1.1763102]

Layer 2 Weights:
 [[ 6.100576 ]
 [-6.5198927]]
Layer 2 Bias:
 [0.00033424]


In [ ]:
import pandas as pd
df=pd.read_csv("/content/fashion-mnist_train.csv")
df.head()

In [ ]:
# ==============================================================
# MLP on Fashion-MNIST Dataset using TensorFlow / Keras
# ==============================================================

import tensorflow as tf
from tensorflow.keras.datasets import fashion_mnist
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Flatten, Dropout
from tensorflow.keras.utils import to_categorical

# --------------------------------------------------------------
# 1️⃣ Load Dataset
# --------------------------------------------------------------
(X_train, y_train), (X_test, y_test) = fashion_mnist.load_data()

print("Training samples:", X_train.shape)
print("Testing samples:", X_test.shape)

# --------------------------------------------------------------
# 2️⃣ Preprocess Data
# --------------------------------------------------------------
# Normalize pixel values (0–255 → 0–1)
X_train = X_train / 255.0
X_test = X_test / 255.0

# Convert labels to one-hot encoding
y_train = to_categorical(y_train, 10)
y_test = to_categorical(y_test, 10)

# --------------------------------------------------------------
# 3️⃣ Build MLP Model
# --------------------------------------------------------------
model = Sequential([
    Flatten(input_shape=(28, 28)),     # Convert 28x28 → 784
    Dense(256, activation='relu'),     # Hidden layer 1
    Dropout(0.2),                      # Prevent overfitting
    Dense(128, activation='relu'),     # Hidden layer 2
    Dense(10, activation='softmax')    # Output layer (10 classes)
])

# --------------------------------------------------------------
# 4️⃣ Compile Model
# --------------------------------------------------------------
model.compile(optimizer='adam',
              loss='categorical_crossentropy',
              metrics=['accuracy'])

# --------------------------------------------------------------
# 5️⃣ Train Model
# --------------------------------------------------------------
history = model.fit(X_train, y_train,
                    epochs=10,
                    batch_size=128,
                    validation_split=0.1,
                    verbose=1)

# --------------------------------------------------------------
# 6️⃣ Evaluate Model
# --------------------------------------------------------------
test_loss, test_acc = model.evaluate(X_test, y_test, verbose=0)
print("\n✅ Test Accuracy:", test_acc)
print("✅ Test Loss:", test_loss)

# --------------------------------------------------------------
# 7️⃣ Make Predictions
# --------------------------------------------------------------
predictions = model.predict(X_test[:5])
print("\nPredicted class probabilities (first 5 samples):\n", predictions)
print("Predicted Classes:", predictions.argmax(axis=1))

# --------------------------------------------------------------
# 8️⃣ Save Model (optional)
# --------------------------------------------------------------
model.save("fashion_mnist_mlp.h5")
print("\nModel saved as fashion_mnist_mlp.h5")
