<a href="https://colab.research.google.com/github/Mohammed-Abdul-Rafe-Sajid/ML-LAB/blob/main/ML_LAB_10.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# ==============================================================
# OR Gate Neural Network using TensorFlow / Keras
# ==============================================================

import numpy as np
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.optimizers import SGD

# --------------------------------------------------------------
# 1️⃣ Prepare Dataset
# --------------------------------------------------------------
X = np.array([[0,0],
              [0,1],
              [1,0],
              [1,1]], dtype=float)

y = np.array([[0],
              [1],
              [1],
              [1]], dtype=float)

# --------------------------------------------------------------
# 2️⃣ Build Model
# --------------------------------------------------------------
model = Sequential()
model.add(Dense(1, input_dim=2, activation='sigmoid'))

# --------------------------------------------------------------
# 3️⃣ Compile Model
# --------------------------------------------------------------
model.compile(optimizer=SGD(learning_rate=0.1),
              loss='binary_crossentropy',
              metrics=['accuracy'])

# --------------------------------------------------------------
# 4️⃣ Train Model
# --------------------------------------------------------------
model.fit(X, y, epochs=5000, verbose=0)

# --------------------------------------------------------------
# 5️⃣ Test Model
# --------------------------------------------------------------
predictions = model.predict(X)
predicted_classes = (predictions > 0.5).astype(int)

print("Inputs:\n", X)
print("Predicted Outputs:\n", predictions)
print("Rounded Predictions (0/1):\n", predicted_classes)

# --------------------------------------------------------------
# 6️⃣ Show Weights and Bias
# --------------------------------------------------------------
weights, bias = model.layers[0].get_weights()
print("\nWeights:\n", weights)
print("Bias:\n", bias)


/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/dense.py:93: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 59ms/step
Inputs:
 [[0. 0.]
 [0. 1.]
 [1. 0.]
 [1. 1.]]
Predicted Outputs:
 [[0.04092794]
 [0.98372185]
 [0.9836459 ]
 [0.99998826]]
Rounded Predictions (0/1):
 [[0]
 [1]
 [1]
 [1]]

Weights:
 [[7.2509427]
 [7.255673 ]]
Bias:
 [-3.1541533]


In [2]:
# ==============================================================
# AND Gate Neural Network using TensorFlow / Keras
# ==============================================================

import numpy as np
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.optimizers import SGD

# --------------------------------------------------------------
# 1️⃣ Prepare Dataset
# --------------------------------------------------------------
X = np.array([[0,0],
              [0,1],
              [1,0],
              [1,1]], dtype=float)

y = np.array([[0],
              [0],
              [0],
              [1]], dtype=float)

# --------------------------------------------------------------
# 2️⃣ Build Model
# --------------------------------------------------------------
model = Sequential()
model.add(Dense(1, input_dim=2, activation='sigmoid'))

# --------------------------------------------------------------
# 3️⃣ Compile Model
# --------------------------------------------------------------
model.compile(optimizer=SGD(learning_rate=0.1),
              loss='binary_crossentropy',
              metrics=['accuracy'])

# --------------------------------------------------------------
# 4️⃣ Train Model
# --------------------------------------------------------------
model.fit(X, y, epochs=5000, verbose=0)

# --------------------------------------------------------------
# 5️⃣ Test Model
# --------------------------------------------------------------
predictions = model.predict(X)
predicted_classes = (predictions > 0.5).astype(int)

print("Inputs:\n", X)
print("Predicted Outputs:\n", predictions)
print("Rounded Predictions (0/1):\n", predicted_classes)

# --------------------------------------------------------------
# 6️⃣ Show Weights and Bias
# --------------------------------------------------------------
weights, bias = model.layers[0].get_weights()
print("\nWeights:\n", weights)
print("Bias:\n", bias)


1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 61ms/step
Inputs:
 [[0. 0.]
 [0. 1.]
 [1. 0.]
 [1. 1.]]
Predicted Outputs:
 [[1.0206445e-04]
 [3.9868936e-02]
 [3.9869867e-02]
 [9.4411135e-01]]
Rounded Predictions (0/1):
 [[0]
 [0]
 [0]
 [1]]

Weights:
 [[6.008356]
 [6.008332]]
Bias:
 [-9.189804]


In [ ]:
# ==============================================================
# XOR Gate Neural Network using TensorFlow / Keras
# ==============================================================

import numpy as np
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.optimizers import SGD

# --------------------------------------------------------------
# 1️⃣ Prepare Dataset
# --------------------------------------------------------------
X = np.array([[0,0],
              [0,1],
              [1,0],
              [1,1]], dtype=float)

y = np.array([[0],
              [1],
              [1],
              [0]], dtype=float)

# --------------------------------------------------------------
# 2️⃣ Build Model (needs hidden layer)
# --------------------------------------------------------------
model = Sequential()
model.add(Dense(2, input_dim=2, activation='sigmoid'))  # hidden layer with 2 neurons
model.add(Dense(1, activation='sigmoid'))               # output layer

# --------------------------------------------------------------
# 3️⃣ Compile Model
# --------------------------------------------------------------
model.compile(optimizer=SGD(learning_rate=0.1),
              loss='binary_crossentropy',
              metrics=['accuracy'])

# --------------------------------------------------------------
# 4️⃣ Train Model
# --------------------------------------------------------------
model.fit(X, y, epochs=10000, verbose=0)

# --------------------------------------------------------------
# 5️⃣ Test Model
# --------------------------------------------------------------
predictions = model.predict(X)
predicted_classes = (predictions > 0.5).astype(int)

print("Inputs:\n", X)
print("Predicted Outputs:\n", predictions)
print("Rounded Predictions (0/1):\n", predicted_classes)

# --------------------------------------------------------------
# 6️⃣ Show Weights and Bias
# --------------------------------------------------------------
for i, layer in enumerate(model.layers):
    weights, bias = layer.get_weights()
    print(f"\nLayer {i+1} Weights:\n", weights)
    print(f"Layer {i+1} Bias:\n", bias)


1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 68ms/step
Inputs:
 [[0. 0.]
 [0. 1.]
 [1. 0.]
 [1. 1.]]
Predicted Outputs:
 [[0.01034662]
 [0.4961489 ]
 [0.98951155]
 [0.5039937 ]]
Rounded Predictions (0/1):
 [[0]
 [0]
 [1]
 [1]]

Layer 1 Weights:
 [[ 3.9434495 -4.236008 ]
 [-7.2929096 -7.180915 ]]
Layer 1 Bias:
 [-2.599403   1.1763102]

Layer 2 Weights:
 [[ 6.100576 ]
 [-6.5198927]]
Layer 2 Bias:
 [0.00033424]


In [ ]:
import pandas as pd
df=pd.read_csv("/content/fashion-mnist_train.csv")
df.head()

In [3]:
# ==============================================================
# MLP on Fashion-MNIST Dataset using TensorFlow / Keras
# ==============================================================

import tensorflow as tf
from tensorflow.keras.datasets import fashion_mnist
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Flatten, Dropout
from tensorflow.keras.utils import to_categorical

# --------------------------------------------------------------
# 1️⃣ Load Dataset
# --------------------------------------------------------------
(X_train, y_train), (X_test, y_test) = fashion_mnist.load_data()

print("Training samples:", X_train.shape)
print("Testing samples:", X_test.shape)

# --------------------------------------------------------------
# 2️⃣ Preprocess Data
# --------------------------------------------------------------
# Normalize pixel values (0–255 → 0–1)
X_train = X_train / 255.0
X_test = X_test / 255.0

# Convert labels to one-hot encoding
y_train = to_categorical(y_train, 10)
y_test = to_categorical(y_test, 10)

# --------------------------------------------------------------
# 3️⃣ Build MLP Model
# --------------------------------------------------------------
model = Sequential([
    Flatten(input_shape=(28, 28)),     # Convert 28x28 → 784
    Dense(256, activation='relu'),     # Hidden layer 1
    Dropout(0.2),                      # Prevent overfitting
    Dense(128, activation='relu'),     # Hidden layer 2
    Dense(10, activation='softmax')    # Output layer (10 classes)
])

# --------------------------------------------------------------
# 4️⃣ Compile Model
# --------------------------------------------------------------
model.compile(optimizer='adam',
              loss='categorical_crossentropy',
              metrics=['accuracy'])

# --------------------------------------------------------------
# 5️⃣ Train Model
# --------------------------------------------------------------
model.fit(X_train, y_train,
                    epochs=10,
                    batch_size=128,
                    validation_split=0.1,
                    verbose=1)

# --------------------------------------------------------------
# 6️⃣ Evaluate Model
# --------------------------------------------------------------
test_loss, test_acc = model.evaluate(X_test, y_test, verbose=0)
print("\n✅ Test Accuracy:", test_acc)
print("✅ Test Loss:", test_loss)

# --------------------------------------------------------------
# 7️⃣ Make Predictions
# --------------------------------------------------------------
predictions = model.predict(X_test[:5])
print("\nPredicted class probabilities (first 5 samples):\n", predictions)
print("Predicted Classes:", predictions.argmax(axis=1))

# --------------------------------------------------------------
# 8️⃣ Save Model (optional)
# --------------------------------------------------------------
model.save("fashion_mnist_mlp.h5")
print("\nModel saved as fashion_mnist_mlp.h5")


29515/29515 ━━━━━━━━━━━━━━━━━━━━ 0s 0us/step
26421880/26421880 ━━━━━━━━━━━━━━━━━━━━ 0s 0us/step
5148/5148 ━━━━━━━━━━━━━━━━━━━━ 0s 0us/step
4422102/4422102 ━━━━━━━━━━━━━━━━━━━━ 0s 0us/step
Training samples: (60000, 28, 28)
Testing samples: (10000, 28, 28)


/usr/local/lib/python3.12/dist-packages/keras/src/layers/reshaping/flatten.py:37: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)


Epoch 1/10
422/422 ━━━━━━━━━━━━━━━━━━━━ 5s 9ms/step - accuracy: 0.7338 - loss: 0.7534 - val_accuracy: 0.8497 - val_loss: 0.4128
Epoch 2/10
422/422 ━━━━━━━━━━━━━━━━━━━━ 4s 9ms/step - accuracy: 0.8567 - loss: 0.3983 - val_accuracy: 0.8608 - val_loss: 0.3764
Epoch 3/10
422/422 ━━━━━━━━━━━━━━━━━━━━ 5s 11ms/step - accuracy: 0.8678 - loss: 0.3663 - val_accuracy: 0.8735 - val_loss: 0.3520
Epoch 4/10
422/422 ━━━━━━━━━━━━━━━━━━━━ 4s 9ms/step - accuracy: 0.8728 - loss: 0.3422 - val_accuracy: 0.8772 - val_loss: 0.3360
Epoch 5/10
422/422 ━━━━━━━━━━━━━━━━━━━━ 4s 9ms/step - accuracy: 0.8827 - loss: 0.3183 - val_accuracy: 0.8810 - val_loss: 0.3249
Epoch 6/10
422/422 ━━━━━━━━━━━━━━━━━━━━ 5s 11ms/step - accuracy: 0.8874 - loss: 0.3078 - val_accuracy: 0.8787 - val_loss: 0.3276
Epoch 7/10
422/422 ━━━━━━━━━━━━━━━━━━━━ 4s 9ms/step - accuracy: 0.8887 - loss: 0.2992 - val_accuracy: 0.8852 - val_loss: 0.3122
Epoch 8/10
422/422 ━━━━━━━━━━━━━━━━━━━━ 5s 9ms/step - accuracy: 0.8916 - loss: 0.2859 - val_accuracy: 


Predicted class probabilities (first 5 samples):
 [[7.18426975e-07 5.59046107e-08 9.73481988e-08 1.32137117e-07
  4.63740477e-08 3.59342725e-04 3.42941291e-07 5.39173186e-03
  3.02208548e-07 9.94247198e-01]
 [3.10640695e-04 8.64119798e-09 9.94349420e-01 8.84624072e-08
  1.28865219e-03 3.56348617e-10 4.05081175e-03 2.19845392e-11
  3.11733231e-07 3.91655762e-12]
 [1.14705823e-09 1.00000000e+00 1.58529370e-11 5.61806690e-09
  1.06431239e-10 3.17514238e-17 5.56808211e-11 2.96070715e-19
  4.51302055e-13 1.85002468e-17]
 [1.30818123e-09 9.99999881e-01 4.05635303e-10 1.13304267e-07
  2.95970415e-10 1.02027564e-15 2.78578327e-10 6.02122180e-18
  9.22387275e-13 1.38520401e-15]
 [1.92859337e-01 1.32445775e-05 1.08061517e-02 1.79803057e-03
  4.38331254e-03 4.70977284e-07 7.90121675e-01 2.30363625e-07
  1.72117452e-05 4.23043389e-07]]
Predicted Classes: [9 2 1 1 6]

Model saved as fashion_mnist_mlp.h5
